apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsaholic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsaholic
      version: 1.0.0
  template:
    metadata:
      labels:
        app: newsaholic
        version: 1.0.0
    spec:
      containers:
        - name: newsaholicconatiner
          image: docker.io/borinhood001/newsaholic_image
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
